server:
  port: 8080

spring:
  # 配置数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC
    username: root
    password: lvshihao
    driver-class-name: com.mysql.jdbc.Driver
  # 配置SprigMvc的试图解析器
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      suffix: .html
      mode: HTML5
      cache: false

# 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

